
root_directory: /home/matthieu.bernard/Documents/IF_to_IMC/ # write path to IF_to_IMC folder

# All paths will be written according to 'root_directory'

# Data linking
data_linking:
  mcd_converter:
    input_dir_raw_mcd: '/home/matthieu.bernard/Documents/IF_to_IMC/data/raw/imc_data/mcd_files'
    output_dir_raw_tiff: '/home/matthieu.bernard/Documents/IF_to_IMC/data/raw/imc_data/patients'
    flush: true
    all_patients: false
    patient: '15T011146-16' # if all_patients: false
    all_rois: true # if false, it will make a file for only the first roi
    markers_combo: false
    all_markers: true
    markers_list: 'Ir191' # will make different files for each marker / ex : 'Ir191,Ir193'

# Neural Network parameters
input_dim: 1
output_dim: 1
batch_size: 32
learning_rate: 0.01 # Karpathy constant 3e-4
train_val_ratio: 0.8

directory_trained_models: './data/nn_data/nn_checkpoints/'
path_training_logs: './data/nn_data/training_logs.csv'
